apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: rabbitmq
    spec:
      {{- with .Values.manager.tolerations }}
      tolerations: {{ toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity: {{ toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 10 }}
      {{- end }}
      containers:
      - args:
        - --health-probe-bind-address=:8081
        command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/rabbitmq/cluster-operator:2.22.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: operator
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: {{ .Values.webhook.port }}
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        {{- if .Values.certManager.enable }}
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: {{ include "cluster-operator.resourceName" (dict "suffix" "webhook-certs" "context" $) }}
          readOnly: true
        {{- end }}
      securityContext:
        {{- if .Values.manager.podSecurityContext }}
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
        {{- else }}
        {}
        {{- end }}
      serviceAccountName: rabbitmq-cluster-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: {{ include "cluster-operator.resourceName" (dict "suffix" "webhook-certs" "context" $) }}
        secret:
          secretName: {{ include "cluster-operator.resourceName" (dict "suffix" "webhook-server-cert" "context" $) }}
